# Generated by Django 4.0.6 on 2022-07-18 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoModulo7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('numero_de_modulos', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 7, 18, 1, 35, 26, 44539), verbose_name='Publicado em')),
            ],
        ),
    ]
