# Generated by Django 4.0.6 on 2022-07-18 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodulo7',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 1, 42, 26, 191295), verbose_name='Publicado em'),
        ),
    ]
