# Generated by Django 4.0.6 on 2022-07-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projetomodulo7_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=50)),
                ('categoria_do_filme', models.CharField(max_length=50)),
                ('Diracao_filme', models.CharField(max_length=50)),
                ('Elenco_filme', models.CharField(max_length=50)),
                ('descricao_filme', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProjetoModulo7',
        ),
    ]
